### ISSUE TITLE
Username lookups for files don't work

### ISSUE THREAD

**Issue by patcon** [ossobv/slackbridge#13]
Mostly filing this as a sanity check in case you're already aware of it.

Take this bug report with a grain of salt, as we're running our own fork: https://github.com/CivicTechTO/slackbridge

![screenshot of bug](https://imgur.com/6Ghed4W.png)

If it becomes a larger concern for us, I'll work on reproducing it and documenting here :)

**Comment by wdoekes** [comment]
Heh, I had seen that, but it didn't register to me as a bug since whole file sharing doesn't work anyway.

Thanks for the report.
