### ISSUE TITLE
[discuss] might you accept some changes upstream?

### ISSUE THREAD

**Issue by patcon** [ossobv/slackbridge#5]
Hi there! Firstly, this is great! Thanks a bunch :)

I've got a fork where I added a few things: https://github.com/ossobv/slackbridge/compare/master...CivicTechTO:heroku-deploy

Main additions are:
1. Ability to more easily deploy to heroku (incl using envvar to config)
2. borrow the concept of "portals" from sameroom.io, which each involve two bidirectional "tunnels". This would strike me as making the normal way of using this tool a little less confusing.

If you'd like to still config via file, I we could later add figaro or dotenv, which accomodates both.

**Comment by patcon** [comment]
Happy to submit PR's if you'd be willing to merge them!

**Comment by wdoekes** [comment]
Hi,

sorry for not responding sooner. I got this during my holidays, and it apparently got lost in my incoming queue.

I'll be happy to merge, if you can clean up the commits to a handful where each commit does one thing properly.

Also: it still has to work for non-heroku setups. Obviously :P
