### ISSUE TITLE
Allow one outgoing webhook to work for all channels

### ISSUE THREAD

**Issue by patcon** [ossobv/slackbridge#9]
Currently, it sems that one Outgoing Webhook is required for each bridged channel. ~~Since free slack instances can only have 10 integrations, this can be limiting.~~ (EDIT: nevermind. having "incoming webhooks" and "outgoing webhooks" only count as **two** integrations, with an arbitrary number of individual configurations for each.)

Outgoing Webhooks can be per-channel or universal. Is there a specific reason that one webhook per team shouldn't be enough for an arbitrary number of channel bridges? (Aside from someone simply not stepping up to do it yet.)

Any advice appreciated, as I assume it will be worth tackling at some point for us :)

**Comment by patcon** [comment]
Given my edit above, this is no longer priority for me anymore, though it would simplify config process a bit :)

**Comment by wdoekes** [comment]
The "outgoing webhook config" has this to say:

> **Integration Settings**
>
> Channel / Optional channel to listen on / Any
>
> Trigger Word(s) / *When a line starts with one of these words, post to the URL(s) below. Optional if a channel is chosen. Separate multiple words with commas.*

If I read that correctly, to listen on multiple channels with the outgoing web hook, you'd have to add "trigger words". That's no good, since I want to listen to everything in that channel.

**Comment by patcon** [comment]
Ah, I missed that. good catch...! I'd say this closes this then ;)

Thanks for everything!
